name: Build

on:
  workflow_dispatch:

jobs:
  backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./schiessmeister-csharp

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore

  frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./schiessmeister-client
    steps:
    - uses: actions/checkout@v4
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: npm
        cache-dependency-path: ./schiessmeister-client/package-lock.json
    - name: Install dependencies
      run: npm ci
    - name: Build
      run: npm run build
