name: Build

on:
  workflow_dispatch:

jobs:
  backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./schiessmeister-csharp

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Setup .NET 7 (for dotnet-project-licenses)
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 7.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      # NuGet License Check
      - name: Check NuGet package licenses
        run: |
          echo "Installing dotnet-project-licenses..."
          dotnet tool install --global dotnet-project-licenses
          export PATH="$PATH:$HOME/.dotnet/tools"
      
          echo "Generating license report..."
          dotnet-project-licenses \
            -i schiessmeister-csharp.csproj \
            -j \
            -o license-report-nuget.json
      
      - name: Debug – Print current directory
        run: |
          echo "Current working directory:"
          pwd
          echo "Files in this directory:"
          ls -lah

          echo ""
          echo "Repository root directory (GITHUB_WORKSPACE):"
          echo $GITHUB_WORKSPACE
          echo "Files in repository root:"
          ls -lah $GITHUB_WORKSPACE
    
      - name: Upload NuGet license report
        uses: actions/upload-artifact@v4
        with:
          name: nuget-license-report
          path: license-report-nuget.json

  frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./schiessmeister-client

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
          cache-dependency-path: ./schiessmeister-client/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      # npm License Check
      - name: Check npm licenses
        run: |
          echo "Checking npm package licenses..."
          npx license-checker-rseidelsohn --summary --failOn "GPL" --production

      - name: Generate license report
        run: |
          npx license-checker-rseidelsohn --json > license-report.json

      - name: Upload license report
        uses: actions/upload-artifact@v4
        with:
          name: npm-license-report
          path: ./schiessmeister-client/license-report.json
